version: '3.8'                          # 版本信息指定使用 Docker Compose 的配置文件版本为 3.8(目前3.8為最新版本)

services: 
  fast-api:                             # 服務名稱
    image: fast-api                     # 使用fastapi 镜像
    container_name: fast-api            # 設置容器名稱為 "fast-api"
    hostname: fast-api                  # 設置主機名稱為 "fast-api"
    ports:                              # 将主机的 5000 端口映射到容器的 5001 端口(這邊要注意:由主機5000端口訪問容器5001端口，此時 dockerfile 設置fastapi應用程式時也要使用5001端口，這樣外部5000才能直接方問到容器內部的fastapi應用程式)
      - 5002:5002
    build:       
      # context: 起始點 (./ --> docker-compose-chain-api.yml目前的路徑)
      context: ./ 
      dockerfile: fast-api/Dockerfile # dockerfile: 要指到dockerfile的路徑
    env_file:                      # 將原本environment設定檔寫成env檔
      - ./config/local.env
    restart: always
    networks:                      # 設置容器使用的網路
      - traefik-proxy
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 400M


networks:
  traefik-proxy:
    external: true
    name: traefik-proxy


