version: '3.8'                 # 版本信息指定使用 Docker Compose 的配置文件版本为 3.8(目前3.8為最新版本)
services:
  # mongo_compass_url = mongodb://mongoadmin:mongoadmin@localhost:27017/
  mongo:                     # 服務名稱
    image: mongo:latest      # 使用最新版的 MongoDB 镜像
    container_name: mongodb  # 設置容器的名稱為 "mongodb"
    hostname: mongodb        # 设置容器的主機名稱 "mongodb"
    restart: always          # 設置容器自動重啟
    networks:                # 設置容器使用的網路
      - traefik-proxy
    ports:                   # 将主机的 27017 端口映射到容器的 27017 端口
      - 27017:27017
    env_file:                # 將原本environment設定檔寫成env檔
      - ../config/local.env
    # volumes: # (選填)儲存在mongo的資料，不會因為container被刪除資料就不見 (volumes要寫在後面，因為前面的配置都在連線與登入)
    #   - ./mongo-database:/data/db

  mongo-express:
    image: mongo-express:latest    # 使用最新版的 mongo-express 镜像
    container_name: mongo-express  # 設置容器的名称为 "mongo-express"
    hostname: mongo-express        # 设置容器的主机名为 "mongo-express"
    restart: always
    networks:                      # 設置容器使用的網路
      - traefik-proxy
    ports:
      - 8081:8081
    env_file:                      # 將原本environment設定檔寫成env檔
      - ../config/local.env


networks:
  traefik-proxy:
    external: true
    name: traefik-proxy